apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  meshName: color-mesh
  listeners:
    - portMapping:
        port: 80
        protocol: http
    - portMapping:
        port: 443
        protocol: http
  serviceDiscovery:
    dns:
      hostName: ingress-nginx.ingress-nginx.svc.cluster.local
  backends:
    - virtualService:
        virtualServiceName: colorteller.appmesh-demo
    - virtualService:
        virtualServiceName: kubernetes.default
